update=23.04.2018 00:59:07
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[eeschema]
version=1
LibDir=../../../Kicad_Lib
[eeschema/libraries]
LibName1=12V_Supply-rescue
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=adc-dac
LibName11=memory
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=D:/Eigene Dateien/Dokumente/Projekte/KiCad/Kicad_Lib/power
LibName32=D:/Eigene Dateien/Dokumente/Projekte/KiCad/Kicad_Lib/w_connectors
LibName33=D:/Eigene Dateien/Dokumente/Projekte/KiCad/Kicad_Lib/w_device
LibName34=D:/Eigene Dateien/Dokumente/Projekte/KiCad/Kicad_Lib/w_transistor
LibName35=D:/Eigene Dateien/Dokumente/Projekte/KiCad/Kicad_Lib/borniers/borniers
LibName36=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName37=C:/Program Files/KiCad/share/kicad/library/74xx
LibName38=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName39=C:/Program Files/KiCad/share/kicad/library/actel
LibName40=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName41=C:/Program Files/KiCad/share/kicad/library/Altera
LibName42=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName43=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName44=C:/Program Files/KiCad/share/kicad/library/atmel
LibName45=C:/Program Files/KiCad/share/kicad/library/audio
LibName46=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName47=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName48=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName49=C:/Program Files/KiCad/share/kicad/library/conn
LibName50=C:/Program Files/KiCad/share/kicad/library/contrib
LibName51=C:/Program Files/KiCad/share/kicad/library/cypress
LibName52=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName53=C:/Program Files/KiCad/share/kicad/library/device
LibName54=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName55=C:/Program Files/KiCad/share/kicad/library/diode
LibName56=C:/Program Files/KiCad/share/kicad/library/display
LibName57=C:/Program Files/KiCad/share/kicad/library/dsp
LibName58=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName59=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName60=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName61=C:/Program Files/KiCad/share/kicad/library/gennum
LibName62=C:/Program Files/KiCad/share/kicad/library/graphic
LibName63=C:/Program Files/KiCad/share/kicad/library/hc11
LibName64=C:/Program Files/KiCad/share/kicad/library/intel
LibName65=C:/Program Files/KiCad/share/kicad/library/interface
LibName66=C:/Program Files/KiCad/share/kicad/library/ir
LibName67=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName68=C:/Program Files/KiCad/share/kicad/library/linear
LibName69=C:/Program Files/KiCad/share/kicad/library/logo
LibName70=C:/Program Files/KiCad/share/kicad/library/maxim
LibName71=C:/Program Files/KiCad/share/kicad/library/memory
LibName72=C:/Program Files/KiCad/share/kicad/library/microchip
LibName73=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName74=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName75=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName76=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName77=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName78=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName79=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName80=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName81=C:/Program Files/KiCad/share/kicad/library/motorola
LibName82=C:/Program Files/KiCad/share/kicad/library/msp430
LibName83=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName84=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName85=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName86=C:/Program Files/KiCad/share/kicad/library/opto
LibName87=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName88=C:/Program Files/KiCad/share/kicad/library/philips
LibName89=C:/Program Files/KiCad/share/kicad/library/power
LibName90=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName91=C:/Program Files/KiCad/share/kicad/library/powerint
LibName92=C:/Program Files/KiCad/share/kicad/library/pspice
LibName93=C:/Program Files/KiCad/share/kicad/library/references
LibName94=C:/Program Files/KiCad/share/kicad/library/regul
LibName95=C:/Program Files/KiCad/share/kicad/library/relays
LibName96=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName97=C:/Program Files/KiCad/share/kicad/library/sensors
LibName98=C:/Program Files/KiCad/share/kicad/library/silabs
LibName99=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName100=C:/Program Files/KiCad/share/kicad/library/stm8
LibName101=C:/Program Files/KiCad/share/kicad/library/stm32
LibName102=C:/Program Files/KiCad/share/kicad/library/supertex
LibName103=C:/Program Files/KiCad/share/kicad/library/switches
LibName104=C:/Program Files/KiCad/share/kicad/library/texas
LibName105=C:/Program Files/KiCad/share/kicad/library/transf
LibName106=C:/Program Files/KiCad/share/kicad/library/transistors
LibName107=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName108=C:/Program Files/KiCad/share/kicad/library/valves
LibName109=C:/Program Files/KiCad/share/kicad/library/video
LibName110=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName111=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName112=C:/Program Files/KiCad/share/kicad/library/Zilog
[general]
version=1
