update=03.02.2018 01:00:42
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=Endstufe-rescue
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=adc-dac
LibName11=memory
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=D:/Eigene Dateien/Dokumente/Projekte/KiCad/Kicad_Lib/w_vacuum
LibName32=D:/Eigene Dateien/Dokumente/Projekte/KiCad/Kicad_Lib/borniers/borniers
LibName33=D:/Eigene Dateien/Dokumente/Projekte/KiCad/Kicad_Lib/w_relay
LibName34=C:/Program Files/KiCad/share/kicad/library/relays
LibName35=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName36=C:/Program Files/KiCad/share/kicad/library/74xx
LibName37=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName38=C:/Program Files/KiCad/share/kicad/library/actel
LibName39=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName40=C:/Program Files/KiCad/share/kicad/library/Altera
LibName41=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName42=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName43=C:/Program Files/KiCad/share/kicad/library/atmel
LibName44=C:/Program Files/KiCad/share/kicad/library/audio
LibName45=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName46=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName47=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName48=C:/Program Files/KiCad/share/kicad/library/conn
LibName49=C:/Program Files/KiCad/share/kicad/library/contrib
LibName50=C:/Program Files/KiCad/share/kicad/library/cypress
LibName51=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName52=C:/Program Files/KiCad/share/kicad/library/device
LibName53=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName54=C:/Program Files/KiCad/share/kicad/library/diode
LibName55=C:/Program Files/KiCad/share/kicad/library/display
LibName56=C:/Program Files/KiCad/share/kicad/library/dsp
LibName57=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName58=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName59=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName60=C:/Program Files/KiCad/share/kicad/library/gennum
LibName61=C:/Program Files/KiCad/share/kicad/library/graphic
LibName62=C:/Program Files/KiCad/share/kicad/library/hc11
LibName63=C:/Program Files/KiCad/share/kicad/library/intel
LibName64=C:/Program Files/KiCad/share/kicad/library/interface
LibName65=C:/Program Files/KiCad/share/kicad/library/ir
LibName66=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName67=C:/Program Files/KiCad/share/kicad/library/linear
LibName68=C:/Program Files/KiCad/share/kicad/library/logo
LibName69=C:/Program Files/KiCad/share/kicad/library/maxim
LibName70=C:/Program Files/KiCad/share/kicad/library/memory
LibName71=C:/Program Files/KiCad/share/kicad/library/microchip
LibName72=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName73=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName74=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName75=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName76=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName77=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName78=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName79=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName80=C:/Program Files/KiCad/share/kicad/library/motorola
LibName81=C:/Program Files/KiCad/share/kicad/library/msp430
LibName82=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName83=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName84=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName85=C:/Program Files/KiCad/share/kicad/library/opto
LibName86=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName87=C:/Program Files/KiCad/share/kicad/library/philips
LibName88=C:/Program Files/KiCad/share/kicad/library/power
LibName89=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName90=C:/Program Files/KiCad/share/kicad/library/powerint
LibName91=C:/Program Files/KiCad/share/kicad/library/pspice
LibName92=C:/Program Files/KiCad/share/kicad/library/references
LibName93=C:/Program Files/KiCad/share/kicad/library/regul
LibName94=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName95=C:/Program Files/KiCad/share/kicad/library/sensors
LibName96=C:/Program Files/KiCad/share/kicad/library/silabs
LibName97=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName98=C:/Program Files/KiCad/share/kicad/library/stm8
LibName99=C:/Program Files/KiCad/share/kicad/library/stm32
LibName100=C:/Program Files/KiCad/share/kicad/library/supertex
LibName101=C:/Program Files/KiCad/share/kicad/library/switches
LibName102=C:/Program Files/KiCad/share/kicad/library/texas
LibName103=C:/Program Files/KiCad/share/kicad/library/transf
LibName104=C:/Program Files/KiCad/share/kicad/library/transistors
LibName105=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName106=C:/Program Files/KiCad/share/kicad/library/valves
LibName107=C:/Program Files/KiCad/share/kicad/library/video
LibName108=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName109=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName110=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName111=D:/KiCadLibs/reed_relais
[general]
version=1
