update=13.08.2015 02:07:18
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=D:/Eigene Dateien/Dokumente/Projekte/KiCad/Kicad_Lib/w_vacuum
LibName31=D:/Eigene Dateien/Dokumente/Projekte/KiCad/Kicad_Lib/borniers/borniers
LibName32=D:/Eigene Dateien/Dokumente/Projekte/KiCad/Kicad_Lib/w_relay
LibName33=C:/Program Files/KiCad/share/kicad/library/relays
LibName34=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName35=C:/Program Files/KiCad/share/kicad/library/74xx
LibName36=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName37=C:/Program Files/KiCad/share/kicad/library/actel
LibName38=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName39=C:/Program Files/KiCad/share/kicad/library/Altera
LibName40=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName41=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName42=C:/Program Files/KiCad/share/kicad/library/atmel
LibName43=C:/Program Files/KiCad/share/kicad/library/audio
LibName44=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName45=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName46=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName47=C:/Program Files/KiCad/share/kicad/library/conn
LibName48=C:/Program Files/KiCad/share/kicad/library/contrib
LibName49=C:/Program Files/KiCad/share/kicad/library/cypress
LibName50=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName51=C:/Program Files/KiCad/share/kicad/library/device
LibName52=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName53=C:/Program Files/KiCad/share/kicad/library/diode
LibName54=C:/Program Files/KiCad/share/kicad/library/display
LibName55=C:/Program Files/KiCad/share/kicad/library/dsp
LibName56=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName57=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName58=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName59=C:/Program Files/KiCad/share/kicad/library/gennum
LibName60=C:/Program Files/KiCad/share/kicad/library/graphic
LibName61=C:/Program Files/KiCad/share/kicad/library/hc11
LibName62=C:/Program Files/KiCad/share/kicad/library/intel
LibName63=C:/Program Files/KiCad/share/kicad/library/interface
LibName64=C:/Program Files/KiCad/share/kicad/library/ir
LibName65=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName66=C:/Program Files/KiCad/share/kicad/library/linear
LibName67=C:/Program Files/KiCad/share/kicad/library/logo
LibName68=C:/Program Files/KiCad/share/kicad/library/maxim
LibName69=C:/Program Files/KiCad/share/kicad/library/memory
LibName70=C:/Program Files/KiCad/share/kicad/library/microchip
LibName71=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName72=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName73=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName74=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName75=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName76=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName77=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName78=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName79=C:/Program Files/KiCad/share/kicad/library/motorola
LibName80=C:/Program Files/KiCad/share/kicad/library/msp430
LibName81=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName82=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName83=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName84=C:/Program Files/KiCad/share/kicad/library/opto
LibName85=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName86=C:/Program Files/KiCad/share/kicad/library/philips
LibName87=C:/Program Files/KiCad/share/kicad/library/power
LibName88=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName89=C:/Program Files/KiCad/share/kicad/library/powerint
LibName90=C:/Program Files/KiCad/share/kicad/library/pspice
LibName91=C:/Program Files/KiCad/share/kicad/library/references
LibName92=C:/Program Files/KiCad/share/kicad/library/regul
LibName93=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName94=C:/Program Files/KiCad/share/kicad/library/sensors
LibName95=C:/Program Files/KiCad/share/kicad/library/silabs
LibName96=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName97=C:/Program Files/KiCad/share/kicad/library/stm8
LibName98=C:/Program Files/KiCad/share/kicad/library/stm32
LibName99=C:/Program Files/KiCad/share/kicad/library/supertex
LibName100=C:/Program Files/KiCad/share/kicad/library/switches
LibName101=C:/Program Files/KiCad/share/kicad/library/texas
LibName102=C:/Program Files/KiCad/share/kicad/library/transf
LibName103=C:/Program Files/KiCad/share/kicad/library/transistors
LibName104=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName105=C:/Program Files/KiCad/share/kicad/library/valves
LibName106=C:/Program Files/KiCad/share/kicad/library/video
LibName107=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName108=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName109=C:/Program Files/KiCad/share/kicad/library/Zilog
